kernel_source: https://github.com/MiCode/Xiaomi_Kernel_OpenSource
kernel_source_branch: onyx-u-oss
kernel_config: onyx_user_defconfig
arch: arm64
compiler: clang
clang_version: r487747c
custom_commands: |
  echo "CONFIG_BT_HCIVHCI=y" >> arch/arm64/configs/onyx_user_defconfig
  echo "CONFIG_USB_G_HID=y" >> arch/arm64/configs/onyx_user_defconfig
  echo "CONFIG_USB_CONFIGFS_F_HID=y" >> arch/arm64/configs/onyx_user_defconfig
