    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/xiaomi-sm8635-devs/android_kernel_xiaomi_onyx
          kernel-branch: lineage-21
          config: onyx_user_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: true
          android-version: 15
          aosp-clang-version: r522815
          ksu: true
          nethunter: true
          
