name: Build Kernel (Onyx GKI)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison binfmt-support libssl-dev libelf-dev libncurses-dev git-lfs

      - name: Download Clang (r510928)
        run: |
          mkdir -p clang
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r510928.tar.gz -o clang.tar.gz
          tar -C clang -xzf clang.tar.gz

      - name: Clone Kernel
        run: |
          git clone --depth=1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource -b onyx-v-oss kernel
          
      - name: Build Kernel
        run: |
          export PATH=$(pwd)/clang/bin:$PATH
          cd kernel
          make ARCH=arm64 O=out onyx_user_defconfig
          make ARCH=arm64 O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
            LLVM=1 \
            LLVM_IAS=1 \
            -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-onyx
          path: kernel/out/arch/arm64/boot/Image
