name: CI
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel for Onyx
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/xiaomi-sm8635-devs/android_kernel_xiaomi_onyx
          kernel-branch: lineage-21
          config: onyx_user_defconfig
          arch: arm64
          # Современные ядра 6.x не используют GCC, только Clang
          aosp-gcc: false
          aosp-clang: true
          # Включаем KernelSU и NetHunter
          ksu: true
          ksu-version: main
          nethunter: true
          # Настройки под твой процессор и Android 16
          android-version: 15
          aosp-clang-version: r522815
          # LTO лучше оставить false для первой успешной сборки
          disable-lto: true
          anykernel3: true
