name: CI

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel for Onyx
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/MiCode/Xiaomi_Kernel_OpenSource
          # Возвращаем твой onyx, раз он определен
          kernel-branch: onyx-v-oss
          config: onyx_user_defconfig
          arch: arm64
          # Включаем GCC (обязательно для этого скрипта)
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          nethunter: true
          android-version: 15
          # Ставим версию Clang, на которой нет ошибки 400
          aosp-clang-version: r530567
          disable-lto: true
          anykernel3: true
